name: ps4-release

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:

  build-ps4-release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install git build-essential cmake zip \
            pacman-package-manager makepkg libarchive-tools autoconf libtool \
            cmake nasm git curl

      - name: Install ps4 toolchain
        run: |
          sudo tee -a /etc/pacman.conf > /dev/null <<EOF
          [pacbrew]
          SigLevel = Optional TrustAll
          Server = https://pacman.mydedibox.fr/pacbrew/packages/
          EOF
          sudo pacman -Syu
          sudo pacman --noconfirm -S ps4-openorbis ps4-openorbis-portlibs

      - name: Configure
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build && cd cmake-build
          export OPENORBIS=/opt/pacbrew/ps4/openorbis
          cmake -G "Unix Makefiles" -DPLATFORM_PS4=ON -DCMAKE_BUILD_TYPE=Release ..

      - name: Build pfbneo
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make pfbneo.deps
          make -j"$(nproc)" pfbneo_pkg
          mv *.pkg $GITHUB_WORKSPACE

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.pkg'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Force Save PS4 PKG to Summary Page
        uses: actions/upload-artifact@v4
        with:
          name: custom-fbneo-ps4-pkg
          path: "**/*.pkg"
